# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ethnicity', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('cause', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
