# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datanyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='count',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cause',
            name='percent',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cause',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
